# Generated by Django 6.0.3 on 2026-04-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_employees_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='worktime_timezone',
            field=models.SmallIntegerField(default=0),
        ),
    ]
