# Generated by Django 6.0.3 on 2026-04-14 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_alter_projects_owner_alter_tasks_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='message',
            field=models.CharField(max_length=256, verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='task_manager.projects'),
        ),
    ]
